name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      MONGODB_URI: mongodb+srv://root:G2t6GIJgMiqJCoLp@cluster01.hhglm5i.mongodb.net/nodeapitest?retryWrites=true&w=majority

    strategy:
      matrix:
        node-version: [16.x] # You can specify multiple versions if needed

    steps:
      - uses: actions/checkout@v2

      # Caching node_modules
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      # Running the linter
      - name: Run Linter
        run: npm run lint

      # Running Unit tests
      - run: npm run test:unit

      # Debugging
      - name: Check if NODE_ENV is set
        run: |
          if [ -z "$NODE_ENV" ]; then
            echo "NODE_ENV is not set!"
          else
            echo "NODE_ENV is set."
          fi

      - name: Check if MONGODB_URI is set
        run: |
          if [ -z "$MONGODB_URI" ]; then
            echo "MONGODB_URI is not set!"
          else
            echo "MONGODB_URI is set."
          fi

      # Running Integration tests
      - run: npm run test:integration
